{% set version = "7.8.1.1" %}
{% set build = 0 %}

package:
  name: neuron
  version: {{ version }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - wheel
    - numpy
  run:
    - python
    - numpy
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - openmpi
  files:
    - Nap_Et2.mod
    - test_mpi.py
  imports:
    - neuron

about:
  home: https://neuron.yale.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright
  summary: NEURON is an empirically-based simulator for modeling neurons and networks of neurons
  doc_url: https://www.neuron.yale.edu/neuron/docs
  dev_url: https://github.com/neuronsimulator/nrn

extra:
  recipe-maintainers:
    - minrk
    - espenhgn
