{% set version = "7.8.1.1" %}
{% set build = 0 %}

package:
  name: neuron
  version: {{ version }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  host: 
    - python
    - pip
    - wheel
    - numpy
  run:
    - python
    - numpy
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
  files:
    - Nap_Et2.mod
  imports:
    - neuron

about:
  home: https://neuron.yale.edu
  license: BSD 3-Clause
  license_family: BSD
  license_file: Copyright
  summary: NEURON is a simulator for models of neurons and networks of neuron.

extra:
  recipe-maintainers:
    - minrk
    - espenhgn
