schema_version: 1

context:
  version: 9.0.1
  build: 1
  mpi_prefix: ${{ 'mpi_' + mpi if mpi != 'nompi' else 'nompi_' }}

package:
  name: neuron
  version: ${{ version }}

source:
  url: https://github.com/neuronsimulator/nrn/releases/download/${{ version }}/nrn-full-src-package-${{ version }}.tar.gz
  sha256: 4bc548655c63c39913ccdc9ff5bdbcdeb040ceb147a5941ae259f42ff06df1b8
  patches:
    # patch cython compiler error
    - d0d1.patch

build:
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi
  number: ${{ build }}
  string: ${{ mpi_prefix }}_h${{ hash }}_${{ build }}
  skip: win
  files:
    exclude:
      # exclude bundled dependencies
      # (these should be dependencies, not bundled at all)
      - include/Eigen/
      - include/Random123/
      - include/fmt/
      - lib/libfmt*
      - lib/cmake/fmt/
      - lib/pkgconfig/fmt*
      # neuron extras
      - share/nrn/demo/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - cmake <4
    - bison
    - flex
    - pkg-config
    - libtool
  host:
    - python
    - cython
    - setuptools
    - pip
    # setup_requires
    - setuptools_scm
    - wheel
    - numpy
    - readline
    - ncurses
    - if: linux
      then:
        - xorg-libx11
        - xorg-libxcomposite
        - xorg-libxext
        - xorg-xorgproto
    - if: mpi != "nompi"
      then: ${{ mpi }}
  run:
    - python
    - numpy
    - packaging
    - readline
    - ncurses
    - setuptools
    - if: mpi != "nompi"
      then:
        - ${{ mpi }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
  run_exports:
    - ${{ pin_subpackage("neuron") }}
    - neuron * ${{ mpi_prefix }}_*

tests:
  - python:
      imports:
        - neuron
        - neuron.rxd
  - files:
      recipe:
        - pump.mod
        - test_mpi.py
        - run_test.sh
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - make
        - scipy
    script:
      content:
        - bash run_test.sh
      env:
        target_platform: ${{ target_platform }}

about:
  license: BSD-3-Clause
  license_file: Copyright
  summary: NEURON is a simulator for models of neurons and networks of neuron.
  homepage: https://neuron.yale.edu

extra:
  recipe-maintainers:
    - minrk
