travis:
  secure:
    BINSTAR_TOKEN: VEGCbTm2MTN5MmJqxGF4bd0dMMqSzRcg53P8pIEyg9Idq6r1Gf1GPb/SO8qp6RcbKmdIPLNbTKYeWD0jUlgviTJ+gcEOia9bIZlbGn20FeweE+zQYwE7e+5wk/uUkzOrDYKiOJ5pSFW4XA7/Pbnsy7+m9EFGkqLvGDp7kQBDpVvctfoOwwuAv6bEUVs8l4AohvpGx3rRiD7G9El9zlvXBs7OONrBgranCK/1A4mzb/x1sqZF0Kud2ZL6EUzRomEAxObVwVBcvcvi+jWCKA3Ob+M5SPmu3nhaw7QmODjInqXxt9ZFADA4NTzV8mZrYq1UuN+FP7YiuXF+303n3V8bGHVmibalCcUqZuGifst59ky/RPJ/US9I9uSOvXEJRGLz1SjN7nVDUWwOdv9p3KnAVXjQOoaiOpruqQkAZ4qXIIpddYCu0gy9iBkPwBohSoDKvhQ+f6HHp7Yj6oYLvEn3l294JTvl6UxU3PHv08Gik6Gbq265GFx892uhss7hLApk0N56DDWKrhu+P0J66uy4JwlQe4gDqDsv+xOn0FPFX8lDCQ36XnVQ4I5LiVl6tBzP5o6AufsCgrLutUufUr+Yc3XpF2yLE7mv8CfnQUAxgwWlW0KtQVOBKW0rHUbQ/ukBj6ZQfO4fvc56IxN38AGDhA4YtV+Gkbamc8tnmYJuCbw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
